# Changes here will be overwritten by Copier
_commit: v3.3.2
_src_path: gh:eccenca/cmem-plugin-template
author_mail: saipraneeth@aarth.io
author_name: Saipraneeth
project_description: This plugin uses OAuth2 to generate access token.
project_slug: auth

