# Changes here will be overwritten by Copier
_commit: v5.0.2
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-auth
project_description: Authenticate to services and provide the OAuth2 access token
    for other tasks.
project_slug: auth
pypi: true

